# Generated by Django 4.2.7 on 2025-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mininguser",
            name="level",
            field=models.ImageField(blank=True, default=1, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="mininguser",
            name="total_points",
            field=models.ImageField(blank=True, default=0, null=True, upload_to=""),
        ),
    ]
