# Generated by Django 4.2.7 on 2025-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_mininguser_level_alter_mininguser_total_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mininguser",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="mininguser",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
