# Generated by Django 4.2.7 on 2025-09-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geological_data", "0002_alter_gravitysurvey_data_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("drill_hole", "Drill Hole Analysis"),
                            ("magnetic_survey", "Magnetic Survey Analysis"),
                            ("gravity_survey", "Gravity Survey Analysis"),
                            ("property_assessment", "Property Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("predicted_grade", models.FloatField(blank=True, null=True)),
                ("anomalies_detected", models.BooleanField(default=False)),
                ("detailed_results", models.JSONField(default=dict)),
                ("ai_interpretation", models.TextField()),
                ("recommendations", models.JSONField(default=list)),
                (
                    "processing_time",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("drilling", "Drilling Data Analyzer"),
                            ("magnetic", "Magnetic Survey Analyzer"),
                            ("gravity", "Gravity Survey Analyzer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("huggingface_model_id", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AITrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        choices=[
                            ("correct", "Correct Prediction"),
                            ("incorrect", "Incorrect Prediction"),
                            ("partially_correct", "Partially Correct"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_analysis.aianalysisresult",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="ai_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai_analysis.aimodel"
            ),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="drill_hole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geological_data.drillhole",
            ),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geological_data.property",
            ),
        ),
    ]
