# Generated by Django 4.2.7 on 2025-09-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrillHole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hole_id", models.CharField(max_length=50)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("total_depth", models.FloatField()),
                ("azimuth", models.FloatField()),
                ("dip", models.FloatField()),
                ("drilling_date", models.DateField()),
                ("ai_processed", models.BooleanField(default=False)),
                ("ai_confidence_score", models.FloatField(blank=True, null=True)),
                ("ai_predicted_grade", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("area_hectares", models.FloatField()),
                ("commodity_focus", models.JSONField(default=list)),
                ("geological_setting", models.TextField()),
                ("access_road", models.BooleanField(default=False)),
                ("power_available", models.BooleanField(default=False)),
                ("exploration_stage", models.CharField(max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MagneticSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_date", models.DateField()),
                ("flight_height", models.FloatField()),
                ("line_spacing", models.FloatField()),
                ("data_file", models.FileField(upload_to="magnetic_surveys/")),
                ("processed_data", models.JSONField(default=dict)),
                ("anomalies_detected", models.IntegerField(default=0)),
                ("ai_interpretation", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geological_data.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GravitySurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_date", models.DateField()),
                ("station_spacing", models.FloatField()),
                ("data_file", models.FileField(upload_to="gravity_surveys/")),
                ("processed_data", models.JSONField(default=dict)),
                ("density_anomalies", models.JSONField(default=list)),
                ("ai_interpretation", models.TextField(blank=True)),
                ("targets_identified", models.IntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geological_data.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrillSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_depth", models.FloatField()),
                ("to_depth", models.FloatField()),
                ("gold_grade", models.FloatField(blank=True, null=True)),
                ("silver_grade", models.FloatField(blank=True, null=True)),
                ("copper_grade", models.FloatField(blank=True, null=True)),
                ("rock_type", models.CharField(max_length=100)),
                ("alteration", models.CharField(blank=True, max_length=200)),
                ("mineralization", models.TextField(blank=True)),
                ("ai_analysis", models.JSONField(default=dict)),
                ("anomaly_detected", models.BooleanField(default=False)),
                (
                    "drill_hole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geological_data.drillhole",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drillhole",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geological_data.property",
            ),
        ),
    ]
