# Generated by Django 4.2.7 on 2025-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geological_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gravitysurvey",
            name="data_file",
            field=models.FileField(blank=True, null=True, upload_to="gravity_surveys/"),
        ),
    ]
